return {
    {'nvim-telescope/telescope.nvim', tag = '0.1.4'},
    {'nvim-lua/plenary.nvim'},
    {"rebelot/kanagawa.nvim"},
    {"tiagovla/tokyodark.nvim"},
    {"shrikecode/kyotonight.vim"},
    {"ayu-theme/ayu-vim"},
    {"rafalbromirski/vim-aurora"},
    {"ghifarit53/tokyonight-vim"},
    {'projekt0n/github-nvim-theme'},
    {"mbbill/undotree"},
    {"tpope/vim-fugitive"},
    {'williamboman/mason.nvim'},
    {'williamboman/mason-lspconfig.nvim'},
    {'VonHeikemen/lsp-zero.nvim', branch = 'v3.x'},
    {'neovim/nvim-lspconfig'},
    {'hrsh7th/cmp-nvim-lsp'},
    {'hrsh7th/nvim-cmp'},
    {'L3MON4D3/LuaSnip'},
    {'wakatime/vim-wakatime'},
}
